---
- name: Setup inWinsible
  hosts: all
  tasks:
    - name: Set Keyboard Language to French
      win_shell: |
        $langList = Get-WinUserLanguageList;
        $langList.Add("fr-FR");
        $langList.Remove("en-US");
        Set-WinUserLanguageList -LanguageList $langList -Force

    - name: Install multiple packages
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        - firefox
        - git
        - vscode
        - processhacker
        - notepadplusplus
        - x64dbg.portable
        - pebear
        - hxd
        - procmon
        - pestudio
      retries: 3

    # https://github.com/AlexNabokikh/windows-playbook
    - name: Unpin 'Search' from Taskbar
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
        name: SearchboxTaskbarMode
        data: 0
        type: dword

    - name: Unpin Task View, Chat and Cortana from Taskbar.
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: "{{ item }}"
        data: 0
        type: dword
      loop:
        - ShowCortanaButton
        - ShowTaskViewButton

    - name: Unpin 'News and Interests' from Taskbar.
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds
        name: EnableFeeds
        data: 0
        type: dword
        state: present

    - name: Unpin 'Edge', 'Store' other built-in shortcuts from Taskbar.
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband
        name: Favorites
        state: absent

    - name: Reboot the machine
      win_reboot:
        reboot_timeout: 3600
